# Generated by Django 4.1.1 on 2022-09-30 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='discount',
            new_name='discount_price',
        ),
    ]
