# Generated by Django 4.1.1 on 2022-10-02 21:03

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "frontend",
            "0008_billingaddress_coupon_order_refund_payment_orderitem_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingaddress",
            name="country",
            field=django_countries.fields.CountryField(
                default="Ukraine", max_length=100
            ),
        ),
    ]
