# Generated by Django 4.1.1 on 2022-10-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0009_alter_billingaddress_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
