# Generated by Django 4.1.1 on 2022-10-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0010_alter_item_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
